export type OrderStatus = {
  CANCELLED: 'CANCELLED';
  PROCESSING: 'PROCESSING';
  PAINTING: 'PAINTING';
  ASSEMBLY: 'ASSEMBLY';
  PACKAGING: 'PACKAGING';
  DELIVERY: 'DELIVERY';
  DONE: 'DONE';
  ARCHIVED: 'ARCHIVED';
};
